import { PromptTemplate } from "@shared/schema";

export const promptTemplates: PromptTemplate[] = [
  // Text-to-Image Templates - Same styles as Remix
  {
    id: "t2i-1",
    title: "Watercolor Style",
    prompt: "Create a beautiful watercolor painting, soft blended colors, artistic brushstrokes, paper texture, impressionist style",
    category: "art",
    modelType: "text-to-image",
  },
  {
    id: "t2i-2",
    title: "Cyberpunk Aesthetic",
    prompt: "Create a cyberpunk scene with neon lights, futuristic elements, dark atmosphere, vibrant pink and cyan colors, dystopian sci-fi aesthetic",
    category: "fantasy",
    modelType: "text-to-image",
  },
  {
    id: "t2i-3",
    title: "Oil Painting Classic",
    prompt: "Create a classical oil painting, rich textures, dramatic lighting, Renaissance art style, museum quality masterpiece",
    category: "art",
    modelType: "text-to-image",
  },
  {
    id: "t2i-4",
    title: "Minimalist Design",
    prompt: "Create minimalist design, clean lines, limited color palette, negative space, modern geometric composition, flat design aesthetic",
    category: "abstract",
    modelType: "text-to-image",
  },
  {
    id: "t2i-5",
    title: "Japanese Anime",
    prompt: "Create in Japanese anime style with bold, colorful energy, stylized features, dynamic poses, and a touch of drama or fantasy",
    category: "art",
    modelType: "text-to-image",
  },
  {
    id: "t2i-6",
    title: "Pixar",
    prompt: "Create in Pixar animation style, expressive characters, animated and alive scenes, warm storybook quality that's both fun and heartfelt",
    category: "art",
    modelType: "text-to-image",
  },
  {
    id: "t2i-7",
    title: "Marvel",
    prompt: "Create in Marvel superhero style with intensity and heroic flair, dynamic poses, cinematic lighting, larger-than-life energy",
    category: "fantasy",
    modelType: "text-to-image",
  },
  {
    id: "t2i-8",
    title: "Origami",
    prompt: "Create origami paper art with clean folds, sharp edges, minimalist charm, delicate geometric look, traditional origami elegance",
    category: "abstract",
    modelType: "text-to-image",
  },
  {
    id: "t2i-9",
    title: "Vaporwave / 90's",
    prompt: "Create vaporwave aesthetic with dreamy neon colors, glitchy textures, retro-futuristic vibes, 90s aesthetics and early internet culture",
    category: "abstract",
    modelType: "text-to-image",
  },
  {
    id: "t2i-10",
    title: "LEGO",
    prompt: "Create LEGO style with blocky shapes, bright colors, playful twist, made entirely from LEGO bricks, toy-like charm full of fun",
    category: "art",
    modelType: "text-to-image",
  },
  {
    id: "t2i-11",
    title: "Studio Ghibli",
    prompt: "Create in Studio Ghibli style with soft lighting, lush landscapes, magic touch, peaceful whimsical world filled with wonder",
    category: "art",
    modelType: "text-to-image",
  },
  {
    id: "t2i-12",
    title: "Sticker",
    prompt: "Create sticker design with bold outlines, bright colors, playful cutout look, clean eye-catching image perfect for digital stickers",
    category: "art",
    modelType: "text-to-image",
  },
  {
    id: "t2i-13",
    title: "Fantasy Storybook",
    prompt: "Create fantasy storybook scene with magical tales, castles, forests, enchanted creatures, soft textures, rich colors, fairytale details",
    category: "fantasy",
    modelType: "text-to-image",
  },
  {
    id: "t2i-14",
    title: "Puppet",
    prompt: "Create puppet style with soft fabrics, stitched features, handmade puppet show feel, theatrical storybook charm crafted from felt and buttons",
    category: "art",
    modelType: "text-to-image",
  },
  
  // Edit Templates - Same styles as Remix
  {
    id: "edit-1",
    title: "Watercolor Style",
    prompt: "Transform into a beautiful watercolor painting, soft blended colors, artistic brushstrokes, paper texture, impressionist style",
    category: "art",
    modelType: "edit",
  },
  {
    id: "edit-2",
    title: "Cyberpunk Aesthetic",
    prompt: "Transform to cyberpunk style with neon lights, futuristic elements, dark atmosphere, vibrant pink and cyan colors, dystopian sci-fi aesthetic",
    category: "fantasy",
    modelType: "edit",
  },
  {
    id: "edit-3",
    title: "Oil Painting Classic",
    prompt: "Transform into a classical oil painting, rich textures, dramatic lighting, Renaissance art style, museum quality masterpiece",
    category: "art",
    modelType: "edit",
  },
  {
    id: "edit-4",
    title: "Minimalist Design",
    prompt: "Simplify into minimalist design, clean lines, limited color palette, negative space, modern geometric composition, flat design aesthetic",
    category: "abstract",
    modelType: "edit",
  },
  {
    id: "edit-5",
    title: "Japanese Anime",
    prompt: "Transform to Japanese anime style with bold, colorful energy, stylized features, dynamic poses, and a touch of drama or fantasy",
    category: "art",
    modelType: "edit",
  },
  {
    id: "edit-6",
    title: "Pixar",
    prompt: "Transform to Pixar animation style, make characters more expressive, scenes feel animated and alive, warm storybook quality",
    category: "art",
    modelType: "edit",
  },
  {
    id: "edit-7",
    title: "Marvel",
    prompt: "Transform to Marvel superhero style with intensity and heroic flair, dynamic poses, cinematic lighting, larger-than-life energy",
    category: "fantasy",
    modelType: "edit",
  },
  {
    id: "edit-8",
    title: "Origami",
    prompt: "Transform to origami paper art with clean folds, sharp edges, minimalist charm, delicate geometric look, traditional origami elegance",
    category: "abstract",
    modelType: "edit",
  },
  {
    id: "edit-9",
    title: "Vaporwave / 90's",
    prompt: "Transform to vaporwave aesthetic with dreamy neon colors, glitchy textures, retro-futuristic vibes, 90s aesthetics surreal nostalgic feel",
    category: "abstract",
    modelType: "edit",
  },
  {
    id: "edit-10",
    title: "LEGO",
    prompt: "Transform to LEGO style with blocky shapes, bright colors, playful twist, made entirely from LEGO bricks, toy-like charm",
    category: "art",
    modelType: "edit",
  },
  {
    id: "edit-11",
    title: "Studio Ghibli",
    prompt: "Transform to Studio Ghibli style with soft lighting, lush landscapes, magic touch, peaceful whimsical world filled with wonder",
    category: "art",
    modelType: "edit",
  },
  {
    id: "edit-12",
    title: "Sticker",
    prompt: "Transform to sticker design with bold outlines, bright colors, playful cutout look, clean eye-catching image perfect for digital stickers",
    category: "art",
    modelType: "edit",
  },
  {
    id: "edit-13",
    title: "Fantasy Storybook",
    prompt: "Transform to fantasy storybook with magical tales, castles, forests, enchanted creatures, soft textures, rich colors, fairytale details",
    category: "fantasy",
    modelType: "edit",
  },
  {
    id: "edit-14",
    title: "Puppet",
    prompt: "Transform to puppet style with soft fabrics, stitched features, handmade puppet show feel, theatrical storybook charm",
    category: "art",
    modelType: "edit",
  },
  
  // Remix Templates
  {
    id: "remix-1",
    title: "Watercolor Style",
    prompt: "Transform into a beautiful watercolor painting, soft blended colors, artistic brushstrokes, paper texture, impressionist style",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-2",
    title: "Cyberpunk Aesthetic",
    prompt: "Reimagine in cyberpunk style with neon lights, futuristic elements, dark atmosphere, vibrant pink and cyan colors, dystopian sci-fi aesthetic",
    category: "fantasy",
    modelType: "remix",
  },
  {
    id: "remix-3",
    title: "Oil Painting Classic",
    prompt: "Transform into a classical oil painting, rich textures, dramatic lighting, Renaissance art style, museum quality masterpiece",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-4",
    title: "Minimalist Design",
    prompt: "Simplify into minimalist design, clean lines, limited color palette, negative space, modern geometric composition, flat design aesthetic",
    category: "abstract",
    modelType: "remix",
  },
  {
    id: "remix-5",
    title: "Japanese Anime",
    prompt: "The Japanese anime style brings your photo to life with anime's bold, colorful energy. It captures the unique charm of animated storytelling from Japan, with stylized features, dynamic poses, and a touch of drama or fantasy.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-6",
    title: "Pixar",
    prompt: "Filled with charm and imagination, this style turns your photo into something straight out of a Pixar film. Characters become more expressive, scenes feel animated and alive, and everything carries a warm, storybook quality that's both fun and heartfelt.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-7",
    title: "Marvel",
    prompt: "Packed with intensity and heroic flair, this style reimagines your photo as part of the Marvel universe. Expect dynamic poses, cinematic lighting, and larger-than-life energy that captures the excitement of epic battles and legendary characters.",
    category: "fantasy",
    modelType: "remix",
  },
  {
    id: "remix-8",
    title: "Origami",
    prompt: "Clean folds, sharp edges, and a minimalist charm define this style, turning your photo into a scene crafted entirely from paper. With a delicate, geometric look, it captures the elegance of traditional origami while giving your image a fresh and artistic twist.",
    category: "abstract",
    modelType: "remix",
  },
  {
    id: "remix-9",
    title: "Vaporwave / 90's",
    prompt: "Dreamy neon colors, glitchy textures, and retro-futuristic vibes define this throwback style. Inspired by 90s aesthetics and early internet culture, it gives your photo a surreal, nostalgic feel, like a lost scene from an old VHS tape or a synthwave album cover.",
    category: "abstract",
    modelType: "remix",
  },
  {
    id: "remix-10",
    title: "LEGO",
    prompt: "With blocky shapes, bright colors, and a playful twist, this style rebuilds your photo as if made entirely from LEGO bricks. Characters become minifigures, and scenes take on a toy-like charm full of fun and creativity.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-11",
    title: "Studio Ghibli",
    prompt: "Soft lighting, lush landscapes, and a magic touch give this style its signature storybook feel. Inspired by the gentle, detailed animation of Studio Ghibli films, it transforms your photo into a peaceful, whimsical world filled with wonder and quiet adventure.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-12",
    title: "Sticker",
    prompt: "Bold outlines, bright colors, and a playful cutout look make this style feel like a fun, peel-and-stick design. It simplifies your photo into a clean, eye-catching image, perfect for digital stickers, journals, or adding personality to your projects.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-13",
    title: "Fantasy Storybook",
    prompt: "Like a page pulled from a magical tale, this style transforms your photo into a whimsical world of castles, forests, and enchanted creatures. Soft textures, rich colors, and fairytale-like details give your image a dreamy, otherworldly feel, perfect for sparking the imagination.",
    category: "fantasy",
    modelType: "remix",
  },
  {
    id: "remix-14",
    title: "Puppet",
    prompt: "Soft fabrics, stitched features, and movable joints give this style the feel of a handmade puppet show. Your photo takes on a theatrical, storybook charm, like a scene brought to life on stage with characters crafted from felt, buttons, and imagination.",
    category: "art",
    modelType: "remix",
  },
];

export const getTemplatesByModel = (modelType: string) => {
  return promptTemplates.filter(t => t.modelType === modelType);
};

export const getTemplatesByCategory = (category: string) => {
  return promptTemplates.filter(t => t.category === category);
};
