import { PromptTemplate } from "@shared/schema";

export const promptTemplates: PromptTemplate[] = [
  // Text-to-Image Templates
  {
    id: "t2i-1",
    title: "Serene Mountain Sunset",
    prompt: "A serene mountain landscape at sunset with snow-capped peaks, dramatic orange and pink sky, reflecting lake in the foreground, ultra realistic, cinematic lighting, 8k quality",
    category: "landscape",
    modelType: "text-to-image",
  },
  {
    id: "t2i-2",
    title: "Professional Portrait",
    prompt: "Professional headshot portrait of a confident person, natural lighting, blurred office background, sharp focus on face, business attire, warm color grading, shot with 85mm lens",
    category: "portrait",
    modelType: "text-to-image",
  },
  {
    id: "t2i-3",
    title: "Abstract Fluid Art",
    prompt: "Abstract fluid art with swirling colors of purple, teal, and gold, smooth gradients, liquid paint texture, contemporary modern art style, high contrast",
    category: "abstract",
    modelType: "text-to-image",
  },
  {
    id: "t2i-4",
    title: "Product Photography",
    prompt: "Professional product photography of a sleek wireless bluetooth speaker, modern minimalist design, white background, studio lighting with soft shadows, commercial quality, high resolution",
    category: "product",
    modelType: "text-to-image",
  },
  {
    id: "t2i-5",
    title: "Modern Architecture",
    prompt: "Modern minimalist architecture exterior, clean geometric lines, glass and concrete materials, natural daylight, surrounded by landscaped garden, architectural photography style",
    category: "architecture",
    modelType: "text-to-image",
  },
  {
    id: "t2i-6",
    title: "Magical Forest",
    prompt: "Enchanted forest with glowing mushrooms, ethereal mist, rays of sunlight filtering through ancient trees, mystical atmosphere, fantasy art style, vibrant colors",
    category: "fantasy",
    modelType: "text-to-image",
  },
  {
    id: "t2i-7",
    title: "Ocean Wave",
    prompt: "Massive ocean wave crashing, turquoise and deep blue water, white foam, dramatic seascape, golden hour lighting, ultra realistic water simulation, 8k detail",
    category: "nature",
    modelType: "text-to-image",
  },
  {
    id: "t2i-8",
    title: "Digital Art Portrait",
    prompt: "Digital art portrait in anime style, vibrant colors, detailed eyes, flowing hair with dynamic movement, soft lighting, expressive character design, high quality illustration",
    category: "art",
    modelType: "text-to-image",
  },
  {
    id: "t2i-9",
    title: "Cosmic Nebula",
    prompt: "Stunning cosmic nebula in deep space, swirling clouds of purple and blue gas, distant stars, galactic dust, ethereal glow, space photography style, ultra high resolution",
    category: "nature",
    modelType: "text-to-image",
  },
  {
    id: "t2i-10",
    title: "Vintage Car",
    prompt: "Classic vintage car from the 1960s, cherry red paint, chrome details, parked on cobblestone street, golden hour lighting, nostalgic atmosphere, automotive photography",
    category: "product",
    modelType: "text-to-image",
  },
  {
    id: "t2i-11",
    title: "Cozy Coffee Shop",
    prompt: "Warm cozy coffee shop interior, wooden furniture, soft ambient lighting, plants on shelves, steam rising from coffee cup, inviting atmosphere, lifestyle photography",
    category: "architecture",
    modelType: "text-to-image",
  },
  {
    id: "t2i-12",
    title: "Dragon Fantasy",
    prompt: "Majestic dragon flying over mountain peaks, detailed scales, spread wings, breathing fire, epic fantasy scene, dramatic clouds, mythical creature, concept art style",
    category: "fantasy",
    modelType: "text-to-image",
  },
  {
    id: "t2i-13",
    title: "Urban Street Art",
    prompt: "Vibrant urban street art mural, graffiti style, bold colors, geometric patterns, modern city wall, contemporary art, high contrast, creative expression",
    category: "art",
    modelType: "text-to-image",
  },
  {
    id: "t2i-14",
    title: "Tropical Beach Paradise",
    prompt: "Pristine tropical beach, crystal clear turquoise water, white sand, palm trees swaying, blue sky with fluffy clouds, peaceful paradise, travel photography",
    category: "landscape",
    modelType: "text-to-image",
  },
  
  // Edit Templates
  {
    id: "edit-1",
    title: "Add Sunset Glow",
    prompt: "Add a warm golden sunset glow to the scene, enhance colors with orange and pink tones, create dramatic lighting",
    category: "nature",
    modelType: "edit",
  },
  {
    id: "edit-2",
    title: "Professional Retouch",
    prompt: "Professional portrait retouching, enhance skin smoothness while maintaining natural texture, brighten eyes, adjust color balance",
    category: "portrait",
    modelType: "edit",
  },
  {
    id: "edit-3",
    title: "Add Snow Effect",
    prompt: "Transform the scene into a winter wonderland, add realistic snow, create cold atmospheric lighting, white and blue color grading",
    category: "landscape",
    modelType: "edit",
  },
  {
    id: "edit-4",
    title: "Enhance Details",
    prompt: "Enhance fine details and sharpness, increase texture clarity, boost color vibrancy, improve overall image quality",
    category: "product",
    modelType: "edit",
  },
  {
    id: "edit-5",
    title: "Add Rain Effect",
    prompt: "Add realistic rain to the scene, create water droplets, wet surfaces, moody atmosphere, overcast lighting",
    category: "nature",
    modelType: "edit",
  },
  {
    id: "edit-6",
    title: "Vintage Film Look",
    prompt: "Transform into vintage film photography, add film grain, warm color grading, slight vignette, nostalgic analog aesthetic",
    category: "art",
    modelType: "edit",
  },
  {
    id: "edit-7",
    title: "Add Bokeh Lights",
    prompt: "Add beautiful bokeh light effects in the background, soft out-of-focus orbs, warm glowing lights, dreamy atmosphere",
    category: "portrait",
    modelType: "edit",
  },
  {
    id: "edit-8",
    title: "Autumn Colors",
    prompt: "Transform the scene with autumn colors, add warm orange and red tones, falling leaves, seasonal atmosphere",
    category: "landscape",
    modelType: "edit",
  },
  {
    id: "edit-9",
    title: "Add Fog Effect",
    prompt: "Add atmospheric fog or mist to the scene, create depth and mystery, soft diffused lighting, ethereal mood",
    category: "nature",
    modelType: "edit",
  },
  {
    id: "edit-10",
    title: "Dramatic B&W",
    prompt: "Convert to dramatic black and white, high contrast, deep shadows, strong highlights, classic monochrome photography",
    category: "art",
    modelType: "edit",
  },
  {
    id: "edit-11",
    title: "Add Neon Glow",
    prompt: "Add vibrant neon glow effects, electric colors, futuristic lighting, cyberpunk atmosphere, glowing edges",
    category: "fantasy",
    modelType: "edit",
  },
  {
    id: "edit-12",
    title: "Golden Hour Magic",
    prompt: "Enhance with golden hour lighting, warm sunset tones, long shadows, magical atmosphere, perfect lighting",
    category: "landscape",
    modelType: "edit",
  },
  {
    id: "edit-13",
    title: "Add Sparkles",
    prompt: "Add magical sparkles and glitter effects, twinkling lights, fairy dust, enchanted atmosphere, dreamy glow",
    category: "fantasy",
    modelType: "edit",
  },
  {
    id: "edit-14",
    title: "Soft Portrait Glow",
    prompt: "Add soft glowing skin, smooth complexion, enhance eyes, warm tones, professional beauty retouch, natural look",
    category: "portrait",
    modelType: "edit",
  },
  
  // Remix Templates
  {
    id: "remix-1",
    title: "Watercolor Style",
    prompt: "Transform into a beautiful watercolor painting, soft blended colors, artistic brushstrokes, paper texture, impressionist style",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-2",
    title: "Cyberpunk Aesthetic",
    prompt: "Reimagine in cyberpunk style with neon lights, futuristic elements, dark atmosphere, vibrant pink and cyan colors, dystopian sci-fi aesthetic",
    category: "fantasy",
    modelType: "remix",
  },
  {
    id: "remix-3",
    title: "Oil Painting Classic",
    prompt: "Transform into a classical oil painting, rich textures, dramatic lighting, Renaissance art style, museum quality masterpiece",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-4",
    title: "Minimalist Design",
    prompt: "Simplify into minimalist design, clean lines, limited color palette, negative space, modern geometric composition, flat design aesthetic",
    category: "abstract",
    modelType: "remix",
  },
  {
    id: "remix-5",
    title: "Japanese Anime",
    prompt: "The Japanese anime style brings your photo to life with anime's bold, colorful energy. It captures the unique charm of animated storytelling from Japan, with stylized features, dynamic poses, and a touch of drama or fantasy.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-6",
    title: "Pixar",
    prompt: "Filled with charm and imagination, this style turns your photo into something straight out of a Pixar film. Characters become more expressive, scenes feel animated and alive, and everything carries a warm, storybook quality that's both fun and heartfelt.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-7",
    title: "Marvel",
    prompt: "Packed with intensity and heroic flair, this style reimagines your photo as part of the Marvel universe. Expect dynamic poses, cinematic lighting, and larger-than-life energy that captures the excitement of epic battles and legendary characters.",
    category: "fantasy",
    modelType: "remix",
  },
  {
    id: "remix-8",
    title: "Origami",
    prompt: "Clean folds, sharp edges, and a minimalist charm define this style, turning your photo into a scene crafted entirely from paper. With a delicate, geometric look, it captures the elegance of traditional origami while giving your image a fresh and artistic twist.",
    category: "abstract",
    modelType: "remix",
  },
  {
    id: "remix-9",
    title: "Vaporwave / 90's",
    prompt: "Dreamy neon colors, glitchy textures, and retro-futuristic vibes define this throwback style. Inspired by 90s aesthetics and early internet culture, it gives your photo a surreal, nostalgic feel, like a lost scene from an old VHS tape or a synthwave album cover.",
    category: "abstract",
    modelType: "remix",
  },
  {
    id: "remix-10",
    title: "LEGO",
    prompt: "With blocky shapes, bright colors, and a playful twist, this style rebuilds your photo as if made entirely from LEGO bricks. Characters become minifigures, and scenes take on a toy-like charm full of fun and creativity.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-11",
    title: "Studio Ghibli",
    prompt: "Soft lighting, lush landscapes, and a magic touch give this style its signature storybook feel. Inspired by the gentle, detailed animation of Studio Ghibli films, it transforms your photo into a peaceful, whimsical world filled with wonder and quiet adventure.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-12",
    title: "Sticker",
    prompt: "Bold outlines, bright colors, and a playful cutout look make this style feel like a fun, peel-and-stick design. It simplifies your photo into a clean, eye-catching image, perfect for digital stickers, journals, or adding personality to your projects.",
    category: "art",
    modelType: "remix",
  },
  {
    id: "remix-13",
    title: "Fantasy Storybook",
    prompt: "Like a page pulled from a magical tale, this style transforms your photo into a whimsical world of castles, forests, and enchanted creatures. Soft textures, rich colors, and fairytale-like details give your image a dreamy, otherworldly feel, perfect for sparking the imagination.",
    category: "fantasy",
    modelType: "remix",
  },
  {
    id: "remix-14",
    title: "Puppet",
    prompt: "Soft fabrics, stitched features, and movable joints give this style the feel of a handmade puppet show. Your photo takes on a theatrical, storybook charm, like a scene brought to life on stage with characters crafted from felt, buttons, and imagination.",
    category: "art",
    modelType: "remix",
  },
];

export const getTemplatesByModel = (modelType: string) => {
  return promptTemplates.filter(t => t.modelType === modelType);
};

export const getTemplatesByCategory = (category: string) => {
  return promptTemplates.filter(t => t.category === category);
};
